"""Define EventParticipant as a full ORM table

Revision ID: fa3331860233
Revises: 0e2519f67551
Create Date: 2025-12-26 01:10:53.804436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fa3331860233'
down_revision = '0e2519f67551'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_user_sessions_refresh_token_hash'))
        batch_op.drop_column('refresh_token_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token_hash', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ux_user_sessions_refresh_token_hash'), ['refresh_token_hash'], unique=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
